### ISSUE TITLE
Blank "." lines in baton

### ISSUE THREAD

**Issue by willwade** [Baton-donation/app#5]
Grid 3 issue. It seems to be adding a lot of "." lines in. 

Here's a video showing it https://acecentreuk.sharepoint.com/:v:/s/AnonymousShares/ES6i4oW70mZHkizhfqJqmToBTpaOWCdd-V-dy65g-DFAKw?e=FucwLT and here's a history file..https://acecentreuk.sharepoint.com/:u:/s/AnonymousShares/EWzA6PauuZpMtmQ71PEpQxgBYAassMV_6K6zJNg80XwUHg?e=7aZVoy

**Comment by gavinhenderson** [comment]
I have a feeling this line of code is probably the cause of this 

https://github.com/Baton-donation/app/blob/1cd2e858e4de0d0b9b190285552bd43c87d71051/main/server/apps/grid.ts#L144
